version: "3"

services:
  app:
    build: .
    container_name: iqos-iluma.com
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=iqos-iluma.com
      - LETSENCRYPT_HOST=iqos-iluma.com
      - LETSENCRYPT_EMAIL=qwe@email.com
    networks:
      - web

networks:
  web:
    external: true
